"""Safe, repeatable scaffolding for bring-your-own-agent integrations."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from dspy_security_bench.integrations.catalog import FrameworkSpec

ENGINE_REF = "v0.10.0"
MANIFEST_PATH = Path(".dspy-security-bench/integration.json")
WORKFLOW_PATH = Path(".github/workflows/dspy-proofrun.yml")
TEST_PATH = Path("tests/test_dspy_security_target.py")

_MODEL_KEYS = {
    "anthropic": "ANTHROPIC_API_KEY",
    "azure": "AZURE_API_KEY",
    "gemini": "GEMINI_API_KEY",
    "google": "GEMINI_API_KEY",
    "openai": "OPENAI_API_KEY",
    "openrouter": "OPENROUTER_API_KEY",
}


@dataclass(frozen=True)
class IntegrationScaffoldResult:
    created: tuple[Path, ...]
    skipped: tuple[Path, ...]
    agent_import: str


def _module_path(module: str) -> Path:
    if not re.fullmatch(r"[A-Za-z_]\w*(\.[A-Za-z_]\w*)*", module):
        raise ValueError("module must be a dotted Python module name")
    return Path(*module.split(".")).with_suffix(".py")


def _runner_parts(runner: str | None) -> tuple[str, str]:
    if not runner or runner.count(":") != 1:
        raise ValueError("MCP/custom integration requires --runner module:callable")
    module_name, callable_name = runner.split(":", 1)
    if not re.fullmatch(r"[A-Za-z_]\w*(\.[A-Za-z_]\w*)*", module_name):
        raise ValueError("runner module must be a dotted Python module name")
    if not re.fullmatch(r"[A-Za-z_]\w*", callable_name):
        raise ValueError("runner callable must be a Python identifier")
    return module_name, callable_name


def _adapter_source(spec: FrameworkSpec, model: str | None, runner: str | None) -> str:
    header = (
        '"""Generated DSPy Security Bench target. Safe to customize and commit."""\n\n'
        "from __future__ import annotations\n\n"
    )
    if spec.key == "mcp":
        module_name, callable_name = _runner_parts(runner)
        return (
            header
            + f'''from {module_name} import {callable_name}\nfrom dspy_security_bench.integrations import CallbackAdapter\n\n\ndef build_agent() -> CallbackAdapter:\n    """Return a fresh benchmark adapter for every case."""\n    return CallbackAdapter(runner={callable_name}, name="mcp-custom-agent")\n'''
        )

    if model is None:
        raise ValueError(f"{spec.label} requires a model")
    return (
        header
        + f'''from dspy_security_bench.integrations import {spec.adapter}\n\n\ndef build_agent() -> {spec.adapter}:\n    """Return a fresh benchmark adapter for every case."""\n    return {spec.adapter}(model={model!r})\n'''
    )


def _test_source(module: str) -> str:
    return f'''"""Zero-network contract checks for the generated security target."""\n\nfrom {module} import build_agent\n\n\ndef test_security_target_returns_fresh_agents():\n    first = build_agent()\n    second = build_agent()\n    assert first is not second\n    assert isinstance(first.name, str) and first.name\n    assert callable(first.run)\n'''


def _provider_keys(spec: FrameworkSpec, model: str | None) -> tuple[str, ...]:
    if model:
        provider = re.split(r"[:/]", model, maxsplit=1)[0].lower()
        if provider in _MODEL_KEYS:
            return (_MODEL_KEYS[provider],)
        if provider.startswith("gpt-") or provider.startswith("o"):
            return ("OPENAI_API_KEY",)
    return spec.required_env


def _workflow_source(agent_import: str, keys: tuple[str, ...]) -> str:
    secrets = ""
    if keys:
        lines = "\n".join(f"      {key}: ${{{{ secrets.{key} }}}}" for key in keys)
        secrets = f"\n    secrets:\n{lines}"
    return f"""# Generated by `dspy-security-bench integrate`.
# Starts manually to avoid unplanned model spend. Add pull_request only after
# choosing a budget, provider-secret policy, and branch protection rule.
name: DSPy Security ProofRun

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  proofrun:
    uses: immu4989/dspy-security-bench/.github/workflows/proofrun.yml@{ENGINE_REF}
    with:
      agent: {agent_import}
      trials: 10
      min-lower-bound: 0.80
      install-project: true{secrets}
"""


def integrate_project(
    spec: FrameworkSpec,
    root: str | Path = ".",
    *,
    model: str | None = None,
    runner: str | None = None,
    module: str = "dspy_security_target",
    include_workflow: bool = True,
    include_test: bool = True,
    force: bool = False,
) -> IntegrationScaffoldResult:
    root = Path(root)
    root_resolved = root.resolve()
    target_relative = _module_path(module)
    agent_import = f"{module}:build_agent"
    chosen_model = model if model is not None else spec.default_model
    keys = _provider_keys(spec, chosen_model)
    manifest = {
        "schema_version": 1,
        "framework": spec.key,
        "agent": agent_import,
        "model": chosen_model,
        "runner": runner,
        "required_import": spec.import_name,
        "required_env": list(keys),
        "package_hint": spec.package_hint,
        "engine_ref": ENGINE_REF,
    }
    targets: list[tuple[Path, str]] = [
        (target_relative, _adapter_source(spec, chosen_model, runner)),
        (MANIFEST_PATH, json.dumps(manifest, indent=2, sort_keys=True) + "\n"),
    ]
    if include_workflow:
        targets.append((WORKFLOW_PATH, _workflow_source(agent_import, keys)))
    if include_test:
        targets.append((TEST_PATH, _test_source(module)))

    created: list[Path] = []
    skipped: list[Path] = []
    pending: list[tuple[Path, str]] = []
    for relative, content in targets:
        path = root / relative
        if path.exists() and not force:
            skipped.append(path)
            continue
        if not path.resolve().is_relative_to(root_resolved):
            raise ValueError(f"refusing to write outside project root through {relative}")
        cursor = path
        while cursor != root:
            if cursor.is_symlink():
                raise ValueError(f"refusing to write through symlink {relative}")
            cursor = cursor.parent
        pending.append((path, content))

    for path, content in pending:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(path)
    return IntegrationScaffoldResult(tuple(created), tuple(skipped), agent_import)
